"""Consolidate the Codex and Claude Chemistry drafts into one candidate list.

Run from the repository root:  python3 agent-data/chemistry/candidates/merge/consolidate.py
Writes candidates.json, candidates.csv and attribution_review.md one level up.
"""

from __future__ import annotations

import csv
import json
import unicodedata
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent
CODEX_PATH = OUT / "codex" / "candidates.json"
CLAUDE_PATH = OUT / "claude-opus-5" / "candidates.json"
ACCESSED = "2026-10-03"


def norm(name: str) -> str:
    s = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode().casefold()
    return "".join(ch for ch in s if ch.isalnum())


# ---------------------------------------------------------------- sources
SOURCES: dict[str, dict] = {}


def wiki(title: str) -> str:
    sid = "wp_" + norm(title)[:40]
    SOURCES[sid] = {
        "title": f"Wikipedia: {title}",
        "url": "https://en.wikipedia.org/wiki/" + title.replace(" ", "_"),
        "accessed_on": ACCESSED,
        "source_type": "encyclopedia_overview",
    }
    return sid


def wikidata(qid: str, label: str) -> str:
    sid = "wd_" + qid
    SOURCES[sid] = {
        "title": f"Wikidata: {label}",
        "url": f"https://www.wikidata.org/wiki/{qid}",
        "accessed_on": ACCESSED,
        "source_type": "registry_living_status",
    }
    return sid


# Deaths verified in this session (Wikidata unless a Wikipedia title is given).
DEATHS = {
    "Axel D. Becke": ("2025-10-23", "Q96596", None),
    "Josef Paldus": ("2023-01-15", "Q6280069", None),
    "John C. H. Spence": ("2021-06-28", "Q20051160", None),
    "Richard Neutze": ("2026-04-28", "Q89107865", None),
    "Richard A. Lerner": ("2021-12-02", "Q509844", None),
    "Sydney Brenner": ("2019-04-05", "Q234463", None),
    "Sigurd Hofmann": ("2022-06-17", "Q109697", None),
    "Roger A. Sheldon": ("2025-10-06", "Q20006798", None),
    "Michael J. Welch": ("2012", "Q90686074", None),
    "Walter Kaminsky": ("2024-11-23", "Q85632", None),
    "Hans-Herbert Brintzinger": ("2019-06-02", "Q1577212", None),
    "Masatake Haruta": ("2022-01-25", "Q1906762", None),
    "Christopher T. Walsh": ("2023-01-10", "Q1086992", None),
    "Fritz Eckstein": ("2026-08-30", "Q1466082", None),
    "Josef Michl": ("2024-05-13", None, "Josef Michl"),
    "Shimon Vega": ("2021-11-16", "Q112035991", None),
    "Watt W. Webb": ("2020-10-29", "Q7974918", None),
    "Roger Fourme": ("2012-12-24", "Q106466145", None),
    "Dante Gatteschi": ("2026-08-11", "Q44553252", None),
    "Scott R. White": ("2018-05-28", "Q43198976", None),
    "Maria Flytzani-Stephanopoulos": ("2019-10-28", "Q29833812", None),
    "Robert West": ("2022-10-12", None, "Robert West (chemist)"),
    "Urs P. Wild": ("2022-11-22", None, "Urs Wild"),
    "Kenneth R. Seddon": ("2018", "Q48294956", None),
    "Christopher M. Dobson": ("2019", None, "Christopher M. Dobson"),
    "Robert H. Grubbs": ("2021-12-19", "Q202140", None),
    "Jean-Michel Savéant": ("2020-08-16", "Q3168146", None),
    "Robert G. Parr": ("2017-03-27", "Q908642", None),
    "Fritz Vögtle": ("2017-01-03", "Q105536", None),
    "Mildred S. Dresselhaus": ("2017-02-20", "Q29573", None),
    "Roger Y. Tsien": ("2016-08-24", "Q200470", None),
    "Allen J. Bard": ("2024-02-11", "Q899517", None),
    "Richard P. Van Duyne": ("2019-07-28", "Q88303612", None),
    "Martin Fleischmann": ("2012-08-03", "Q899264", None),
    "Aaron Klug": ("2018-11-20", "Q190626", None),
    "Alfred P. Wolf": ("1998", "Q4723260", None),
    "Henry N. Wagner Jr.": ("2012-09-25", "Q20675537", None),
    "Richard E. Smalley": ("2005-10-28", "Q106746", None),
    "H. Allen O. Hill": ("2021-07-30", "Q5929839", None),
    "Nadrian C. Seeman": ("2021-11-16", "Q6593045", None),
    "Robert L. Letsinger": ("2014-05-26", "Q2157952", None),
    "Kenichi Honda": ("2011-02-26", "Q11519983", None),
    "Robin M. Hochstrasser": ("2013-02-27", "Q15990046", None),
    "Calvin F. Quate": ("2019-07-06", "Q482334", None),
    "Dieter Oesterhelt": ("2022-11-28", "Q1222570", None),
}


def hist(name: str, contribution: str, extra_sources: list[str] | None = None) -> dict:
    date, qid, wp = DEATHS.get(name, (None, None, None))
    sids = list(extra_sources or [])
    if qid:
        sids.append(wikidata(qid, f"{name} (date of death {date})"))
    elif wp:
        sids.append(wiki(wp))
    return {
        "name": name,
        "contribution": contribution,
        "death_date": date,
        "source_ids": sids,
        "eligible_credit_pool": False,
    }


# ---------------------------------------------------------------- inputs
codex = json.loads(CODEX_PATH.read_text())
claude = json.loads(CLAUDE_PATH.read_text())
CX = {c["candidate_id"]: c for c in codex["candidates"]}
CL = {c["candidate_id"]: c for c in claude["candidates"]}
for sid, src in codex["sources"].items():
    SOURCES[sid] = src

# Codex historical contributors carry their own death sources; map to contributions.
CODEX_HIST_CONTRIB = {
    "Calvin F. Quate": "Co-inventor of the atomic force microscope",
    "Hiroshi Ito": "Co-inventor of chemically amplified resists",
    "Nadrian C. Seeman": "Founder of structural DNA nanotechnology",
    "Robert L. Letsinger": "Co-developer of DNA-nanoparticle conjugates",
    "Dieter Oesterhelt": "Microbial rhodopsin biochemistry",
    "Jiří Čížek": "Introduced coupled-cluster theory into quantum chemistry",
    "Josef Paldus": "Coupled-cluster theory development",
    "Kenichi Honda": "Honda-Fujishima photoelectrochemical water splitting",
    "Kiyoshi Nagai": "Spliceosome structural biology",
    "Robin M. Hochstrasser": "Multidimensional infrared spectroscopy",
}

# ---------------------------------------------------------------- merged entries
# Each Codex entry is retained. `claude` lists matched Claude draft entries;
# `add` puts supported Claude names into the pool; `drop` removes names from the
# Codex pool; `hist` adds historical-only contributors; `note` is appended to
# the attribution note; `discovery`/`subfield` override the Codex wording.
MERGE: dict[str, dict] = {
    "C001": dict(claude=["c38"], add=["Weitao Yang", "Donald G. Truhlar"], drop=["Axel D. Becke"],
                 hist=[("Axel D. Becke", "Gradient-corrected and hybrid exchange functionals"),
                       ("Robert G. Parr", "Density-functional theory of atoms and molecules")],
                 note="Axel Becke died on 23 October 2025 and is moved to historical credit; this removes the hybrid-functional lineage's leading living claimant. Claude added Weitao Yang and Donald Truhlar as alternative functional-development credit."),
    "C002": dict(claude=["c08"], add=["Herman S. Overkleeft", "Eranthie Weerapana"],
                 note="Claude added Overkleeft (activity-based probe chemistry) and Weerapana (quantitative cysteine reactivity profiling with Cravatt)."),
    "C003": dict(claude=["c80"]),
    "C004": dict(claude=["c16"], note="Claude drafted ATRP and RAFT as one 'controlled radical polymerization' entry (Matyjaszewski, Sawamoto, Rizzardo); kept as two entries per the Codex attribution guidance. A combined citation must choose across both pools."),
    "C054": dict(claude=["c16"], note="See the ATRP entry: Claude's combined controlled-radical-polymerization entry maps to both."),
    "C006": dict(claude=["c54"], add=["Rohit V. Pappu", "Tanja Mittag"],
                 note="Claude added Pappu and Mittag for the physical-chemical (sticker-spacer) theory and sequence grammar of condensates."),
    "C012": dict(claude=["c18"], add=["Craig J. Hawker"], hist=[("Fritz Vögtle", "First cascade (dendritic) synthesis, 1978")],
                 note="Claude added Hawker (convergent synthesis with Fréchet)."),
    "C013": dict(claude=["c27"], add=["Stacey I. Zones", "Jihong Yu", "Michael Tsapatsis"],
                 conflict=["Probable coauthorship between committee member Xiaodong Zou (zeolite structure determination by electron crystallography) and Avelino Corma on new zeolite frameworks; verify before dispatch."],
                 note="Claude added Zones (organic structure-directing agents), Jihong Yu and Tsapatsis."),
    "C014": dict(claude=["c46"], add=["Morinobu Endo"],
                 hist=[("Mildred S. Dresselhaus", "Theory of carbon nanotube electronic structure"),
                       ("Richard E. Smalley", "Nanotube synthesis; 1996 Chemistry laureate for fullerenes")],
                 note="Claude added Endo for catalytic vapour-grown carbon fibres and nanotubes."),
    "C015": dict(claude=["c13"], add=["Hao Yan", "Peng Yin"],
                 note="Claude added Hao Yan (DNA origami architectures) and Peng Yin (single-stranded tile assembly)."),
    "C016": dict(claude=["c72"], add=["A. Paul Alivisatos"],
                 note="Alivisatos added as the independent 1996 DNA-nanocrystal assembly claimant the Codex note mentions; Mirkin's dip-pen nanolithography is a separate achievement."),
    "C017": dict(claude=["c64"], add=["Dario Neri", "Kim D. Janda", "Barry A. Morgan"],
                 discovery="DNA-encoded and DNA-programmed small-molecule libraries",
                 hist=[("Richard A. Lerner", "Encoded combinatorial chemistry (with Brenner, 1992)"),
                       ("Sydney Brenner", "Encoded combinatorial chemistry concept")],
                 note="Merged with Claude's DNA-encoded library entry: Neri (DNA-encoded libraries in drug discovery), Janda (encoded combinatorial chemistry) and Morgan (industrial DEL platform). DNA-templated synthesis (Liu, Harbury) and DEL screening are separable citations."),
    "C019": dict(claude=["c30"], add=["Anders Hagfeldt"],
                 note="Claude added Hagfeldt for DSSC device chemistry. Shozo Yanagida (Claude other_names) left out because living status could not be verified."),
    "C020": dict(claude=["c02"], add=["John J. Kasianowicz"],
                 note="Claude added Kasianowicz, first author of the 1996 alpha-hemolysin polynucleotide translocation paper."),
    "C021": dict(claude=["c06"], add=["Lei Wang", "Ryan A. Mehl", "Shigeyuki Yokoyama"],
                 note="Claude added Lei Wang (first in vivo unnatural amino acid incorporation, with Schultz), Mehl and Yokoyama."),
    "C024": dict(claude=["c39"], note="Claude drafted Car-Parrinello dynamics and metadynamics as one entry; kept separate."),
    "C041": dict(claude=["c39"]),
    "C025": dict(claude=["c106"]),
    "C027": dict(claude=["c31"], add=["Sang Il Seok", "Mercouri G. Kanatzidis"],
                 note="Claude added Seok (high-efficiency solution processing) and Kanatzidis (early solid-state perovskite cells)."),
    "C028": dict(claude=["c42"], add=["Lyndon Emsley", "Geoffrey Bodenhausen", "Thomas Prisner"],
                 hist=[("Shimon Vega", "Solid-state NMR and DNP theory")],
                 note="Claude added Emsley and Bodenhausen (DNP-enhanced NMR of surfaces and materials) and Prisner (DNP instrumentation)."),
    "C030": dict(claude=["c90"], add=["Gerald F. Joyce"]),
    "C031": dict(claude=["c20"], note="Claude drafted one C-H activation entry spanning both Codex entries; kept as two."),
    "C036": dict(claude=["c20"], add=["John F. Hartwig", "Melanie S. Sanford", "Olafs Daugulis", "Milton R. Smith III"],
                 note="Claude added Hartwig and Smith (catalytic C-H borylation), Sanford (Pd-catalysed directed C-H oxidation) and Daugulis (auxiliary-directed C-H functionalization). Shinji Murai (Ru-catalysed directed C-H addition, 1993) left out because living status could not be verified."),
    "C032": dict(claude=["c68"], add=["Bruce Dunn"],
                 note="Claude drafted MXenes and pseudocapacitive storage as one entry; kept separate. Dunn added for pseudocapacitance."),
    "C044": dict(claude=["c68"]),
    "C033": dict(claude=["c14"], add=["Daniel G. Anderson", "Robert S. Langer"],
                 note="Claude added Anderson and Langer for combinatorial discovery of ionizable lipids."),
    "C034": dict(claude=["c23"], add=["Steven P. Nolan", "Tomislav Rovis", "Jeffrey W. Bode"],
                 hist=[("Robert H. Grubbs", "NHC ligands in metathesis catalysts; 2005 Chemistry laureate")],
                 note="Claude added Nolan (NHC transition-metal catalysis) and Rovis and Bode (NHC organocatalysis); these are separable citations."),
    "C038": dict(claude=["c35"], note="Stephan Isied and Gerald McLendon (Claude other_names) left out because living status could not be verified."),
    "C039": dict(claude=["c09"], add=["Steven P. Gygi", "Donald F. Hunt", "Albert J. R. Heck"]),
    "C040": dict(claude=["c01"], add=["Jingyue Ju", "Jonathan M. Rothberg"],
                 note="Claude added Ju (cleavable fluorescent reversible terminators) and Rothberg (454 pyrosequencing) as competing-priority names."),
    "C042": dict(claude=["c29"], add=["Jonathan R. Nitschke", "Michael D. Ward"]),
    "C045": dict(claude=["c11"], add=["Ashraf Brik", "Lei Liu", "Samuel J. Danishefsky"]),
    "C046": dict(claude=["c32"], add=["Richard H. Friend", "Jeremy H. Burroughes"],
                 discovery="Organic and polymer electroluminescent diodes",
                 note="Merged with Claude's OLED entry, which adds the 1990 polymer LED (Friend, Burroughes); small-molecule and polymer devices are separable citations."),
    "C068": dict(claude=["c32"], add=["Chihaya Adachi"],
                 discovery="Triplet harvesting in organic light-emitting devices",
                 note="Claude added Adachi for thermally activated delayed fluorescence, a second triplet-harvesting route."),
    "C047": dict(claude=["c21"], add=["Masanori Kosugi"],
                 note="Claude added Kosugi (Kosugi-Migita tin-amide amination, 1983). Toshihiko Migita left out because living status could not be verified."),
    "C049": dict(claude=["c40"], add=["Krishnan Raghavachari", "Hans-Joachim Werner", "Martin Head-Gordon"],
                 note="Claude added Raghavachari (CCSD(T)), Werner and Head-Gordon."),
    "C050": dict(claude=["c04"], add=["Keiji Nishida", "Akihiko Kondo"],
                 note="Claude added Nishida and Kondo for the parallel Target-AID cytidine base editor (2016)."),
    "C051": dict(claude=["c04"]),
    "C052": dict(claude=["c07"], add=["Alessio Ciulli", "Hiroshi Handa", "Takumi Ito", "Nathanael S. Gray"],
                 discovery="Targeted protein degradation by PROTACs and molecular glue degraders",
                 note="Merged with Claude's broader entry: Ciulli (VHL-ligand degraders and ternary-complex structures), Handa and Ito (cereblon as the thalidomide target) and Gray (degrader chemistry)."),
    "C053": dict(claude=["c65"], add=["Lewis E. Kay", "Gerhard Wagner", "Arthur G. Palmer III"],
                 discovery="Solution NMR methods for the structure and dynamics of large biomolecules",
                 note="Merged with Claude's NMR-dynamics entry: Kay (methyl-TROSY and relaxation dispersion), Wagner and Palmer. RDCs and dynamics methods are separable citations. Konstantin Pervushin (TROSY) left out because living status could not be verified."),
    "C055": dict(claude=["c10"], add=["Guifang Jia", "Yun-Gui Yang"]),
    "C056": dict(claude=["c48"], add=["George M. Whitesides", "Younan Xia"],
                 discovery="Self-assembled monolayers and soft lithography for molecular control of surfaces",
                 note="Claude added Whitesides and Xia (alkanethiol SAMs and soft lithography); soft lithography is separable from the SAM discovery."),
    "C057": dict(claude=["c33"], add=["Kazunari Domen"], hist=[("Allen J. Bard", "Semiconductor photoelectrochemistry")],
                 note="Claude added Domen for particulate photocatalysts for overall water splitting."),
    "C058": dict(claude=["c82"], add=["Xiaowei Zhuang"]),
    "C060": dict(claude=["c70"], add=["Gerald R. Crabtree"],
                 note="Claude added Crabtree (chemically induced dimerization with Schreiber). Thomas Wandless left out because living status could not be verified."),
    "C063": dict(claude=["c63"], add=["Phil S. Baran", "Erick M. Carreira", "Larry E. Overman", "Steven V. Ley"]),
    "C064": dict(claude=["c97"], add=["Holger Stark"]),
    "C066": dict(claude=["c75"], add=["Jun Li", "Abhaya K. Datye"],
                 hist=[("Maria Flytzani-Stephanopoulos", "Atomically dispersed gold and platinum catalysts")],
                 note="Claude added Jun Li (Tsinghua; theory of the 2011 Pt1/FeOx catalyst) and Datye (atom trapping). The Jun Li in this pool is the Tsinghua theoretical chemist."),
    "C067": dict(claude=["c28"], add=["Ryong Ryoo", "Shinji Inagaki"]),
    "C069": dict(claude=["c78"], add=["George C. Schatz", "Younan Xia"],
                 discovery="Plasmonic nanoparticles: tunable optical properties and light-driven chemistry"),
    "C070": dict(claude=["c44"], add=["Andrei Tokmakoff", "Shaul Mukamel", "Graham R. Fleming"]),
    "C071": dict(claude=["c25"], add=["Paolo Melchiorre", "Shunichi Fukuzumi", "Burkhard König"]),
    "C072": dict(claude=["c105"], note="Claude drafted vitrimers and autonomic self-healing together; self-healing is a separate entry."),
}

# ---------------------------------------------------------------- Claude-only entries
CL_ONLY = [
    dict(src="c03", key="phosphoramidite-synthesis",
         discovery="Phosphoramidite chemistry for automated DNA synthesis",
         subfield="Nucleic acid chemistry",
         names=["Marvin H. Caruthers", "Leroy E. Hood"],
         hist=[("Robert L. Letsinger", "Phosphite-triester oligonucleotide chemistry")],
         basis="Solid-phase phosphoramidite coupling made DNA oligonucleotides routine and automatable.",
         rationale="Underpins PCR primers, sequencing, gene synthesis and oligonucleotide drugs.",
         reservation="An enabling method; credit is shared with Letsinger's phosphite chemistry and instrument developers.",
         attribution="Caruthers (phosphoramidite chemistry with Beaucage); Hood for the automated synthesizer.",
         sources=["Oligonucleotide synthesis", "Marvin H. Caruthers"]),
    dict(src="c05", key="crispr-adaptive-immunity",
         discovery="CRISPR-Cas as a bacterial adaptive immune system",
         subfield="Microbial and nucleic acid biochemistry",
         names=["Francisco J. M. Mojica", "Rodolphe Barrangou", "Virginijus Šikšnys", "Philippe Horvath", "Eugene V. Koonin", "John van der Oost", "Feng Zhang"],
         basis="CRISPR loci acquire spacers from invaders and guide Cas nucleases to destroy matching nucleic acids.",
         rationale="The biological discovery behind genome editing, distinct from the 2020 editing-tool award.",
         reservation="The 2020 Chemistry prize rewarded CRISPR-Cas9 genome editing; a second CRISPR award needs a clearly separate citation.",
         attribution="Mojica (CRISPR as immunity hypothesis), Barrangou and Horvath (experimental proof), Šikšnys (Cas9 biochemistry), Koonin and van der Oost (mechanistic classification), Zhang (Cas12a and mammalian editing).",
         prior=["CRISPR-Cas9 genome editing: Chemistry 2020; substantial overlap review"],
         sources=["CRISPR", "Francisco Mojica"]),
    dict(src="c12", key="automated-glycan-assembly",
         discovery="Automated glycan assembly and synthetic carbohydrate vaccines",
         subfield="Carbohydrate chemistry and glycoscience",
         names=["Peter H. Seeberger", "Chi-Huey Wong", "Laura L. Kiessling", "Daniel E. Kahne", "Geert-Jan Boons"],
         basis="Automated solid-phase and programmable one-pot methods made defined oligosaccharides accessible.",
         rationale="Opened glycan arrays, synthetic vaccines and chemical glycobiology.",
         reservation="Partly overlaps the 2022 bioorthogonal/glycoscience context; impact is narrower than nucleic-acid synthesis.",
         attribution="Seeberger (automated glycan assembly), Wong (programmable one-pot synthesis, glycan arrays); Kiessling, Kahne and Boons as alternative glycoscience credit.",
         sources=["Peter Seeberger", "Carbohydrate synthesis"]),
    dict(src="c15", key="polymeric-controlled-release",
         discovery="Polymeric controlled release of macromolecular drugs",
         subfield="Polymer and pharmaceutical chemistry",
         names=["Robert S. Langer", "Nicholas A. Peppas", "Kazunori Kataoka", "María José Alonso"],
         basis="Biocompatible polymers can release proteins and other macromolecules at controlled rates.",
         rationale="Foundation of drug-delivery science, with long clinical use.",
         reservation="A broad field label; the Codex draft deliberately did not expand drug delivery into separate entries.",
         attribution="Langer (macromolecule release from polymers), Peppas (hydrogels), Kataoka (polymeric micelles), Alonso (nanocarriers).",
         sources=["Robert S. Langer", "Drug delivery"]),
    dict(src="c17", key="single-site-olefin-polymerization",
         discovery="Single-site molecular catalysts for stereocontrolled olefin polymerization",
         subfield="Organometallic and polymer chemistry",
         names=["Tobin J. Marks", "John E. Bercaw", "Geoffrey W. Coates", "Maurice Brookhart", "Robert M. Waymouth"],
         hist=[("Walter Kaminsky", "Methylaluminoxane-activated metallocene catalysts"),
               ("Hans-Herbert Brintzinger", "Chiral ansa-metallocenes for isotactic polypropylene")],
         basis="Well-defined metallocene and late-metal catalysts control polymer tacticity and composition at the molecular level.",
         rationale="Transformed polyolefin manufacture and connected molecular structure to polymer properties.",
         reservation="The two clearest discoverers, Kaminsky and Brintzinger, are dead; Ziegler-Natta catalysis was rewarded in 1963.",
         attribution="Marks (cationic metallocene activation), Bercaw (mechanism), Coates and Waymouth (stereocontrol), Brookhart (late-metal diimine catalysts).",
         prior=["Ziegler-Natta polymerization: Chemistry 1963"],
         sources=["Metallocene", "Kaminsky catalyst"]),
    dict(src="c19", key="supramolecular-polymers",
         discovery="Supramolecular polymers and self-assembling molecular nanostructures",
         subfield="Supramolecular and polymer chemistry",
         names=["Takuzo Aida", "Samuel I. Stupp", "E. W. Meijer"],
         basis="Directional non-covalent bonds assemble monomers into polymer-like and functional nanostructures.",
         rationale="A materials extension of supramolecular chemistry with biomaterials and electronics applications.",
         reservation="Supramolecular chemistry was rewarded in 1987 and molecular machines in 2016.",
         attribution="Meijer (quadruple hydrogen-bonded supramolecular polymers), Stupp (peptide amphiphiles), Aida (aqua materials and nanotubes).",
         prior=["Supramolecular chemistry: Chemistry 1987"],
         sources=["Supramolecular polymer"]),
    dict(src="c22", key="frustrated-lewis-pairs",
         discovery="Frustrated Lewis pairs and metal-free activation of small molecules",
         subfield="Main-group chemistry",
         names=["Douglas W. Stephan", "Gerhard Erker"],
         basis="Sterically prevented Lewis acid-base pairs split H2 and activate other small molecules without metals.",
         rationale="Made main-group compounds behave like transition-metal catalysts.",
         reservation="Industrial impact is still modest.",
         attribution="Stephan reported reversible metal-free H2 activation (2006); Erker extended FLP chemistry.",
         sources=["Frustrated Lewis pair"]),
    dict(src="c24", key="hydrogen-bond-donor-catalysis",
         discovery="Hydrogen-bond-donor and chiral Brønsted acid asymmetric catalysis",
         subfield="Asymmetric catalysis",
         names=["Eric N. Jacobsen", "Masahiro Terada", "Takahiko Akiyama", "Hisashi Yamamoto"],
         basis="Chiral thioureas and phosphoric acids catalyse enantioselective reactions through hydrogen bonding and ion pairing.",
         rationale="A major branch of small-molecule asymmetric catalysis.",
         reservation="Asymmetric organocatalysis was rewarded in 2021 (List, MacMillan); overlap is substantial.",
         attribution="Jacobsen (thiourea catalysis), Akiyama and Terada (chiral phosphoric acids, 2004), Yamamoto (Brønsted and Lewis acid catalysis).",
         prior=["Asymmetric organocatalysis: Chemistry 2021; substantial overlap"],
         sources=["Thiourea organocatalysis", "Eric Jacobsen (chemist)"]),
    dict(src="c26", key="molecular-nitrogen-fixation",
         discovery="Earth-abundant-metal catalysis and molecular catalytic nitrogen fixation",
         subfield="Inorganic chemistry and catalysis",
         names=["Paul J. Chirik", "Yoshiaki Nishibayashi", "Jonas C. Peters", "Patrick L. Holland", "Richard R. Schrock"],
         basis="Well-defined molecular complexes catalyse N2 reduction to ammonia, and iron and cobalt catalysts replace precious metals.",
         rationale="Fundamental small-molecule activation with sustainability relevance.",
         reservation="Two linked but separable topics; practical ammonia synthesis remains Haber-Bosch.",
         attribution="Schrock (first molecular catalytic N2 reduction, 2003), Nishibayashi and Peters (later catalysts), Chirik (iron/cobalt catalysis), Holland (iron-N2 chemistry).",
         prior=["Schrock: Chemistry 2005 for olefin metathesis; distinct achievement"],
         sources=["Abiological nitrogen fixation using homogeneous catalysts", "Paul Chirik"]),
    dict(src="c34", key="proton-coupled-electron-transfer",
         discovery="Proton-coupled electron transfer: theory and molecular electrocatalysis",
         subfield="Physical and inorganic chemistry",
         names=["Sharon Hammes-Schiffer", "Thomas J. Meyer", "James M. Mayer", "Daniel G. Nocera"],
         hist=[("Jean-Michel Savéant", "Electrochemical theory of concerted proton-electron transfer")],
         basis="Coupled proton and electron movement governs energy conversion in enzymes and catalysts.",
         rationale="Extends Marcus theory to the reactions behind photosynthesis, respiration and fuel catalysis.",
         reservation="Electron-transfer theory was rewarded in 1992.",
         attribution="Hammes-Schiffer (theory), Meyer (term and molecular PCET), Mayer (thermochemistry), Nocera.",
         prior=["Electron-transfer theory (Marcus): Chemistry 1992"],
         sources=["Proton-coupled electron transfer"]),
    dict(src="c36", key="solar-fuels-catalysts",
         discovery="Molecular catalysts and integrated devices for solar fuel production",
         subfield="Inorganic chemistry and energy catalysis",
         names=["Daniel G. Nocera", "Marc Fontecave", "Clifford P. Kubiak", "Licheng Sun"],
         basis="Molecular and self-healing catalysts drive water oxidation and CO2 reduction in artificial photosynthesis.",
         rationale="Energy-relevant catalysis.",
         reservation="Diffuse credit and limited deployment; overlaps the water-splitting and PCET entries.",
         attribution="Nocera (cobalt-phosphate catalyst, artificial leaf), Sun (molecular Ru water-oxidation catalysts), Fontecave and Kubiak (CO2 reduction).",
         sources=["Artificial photosynthesis", "Daniel G. Nocera"]),
    dict(src="c37", key="catalysis-descriptors",
         discovery="Computational descriptors for the design of heterogeneous catalysts",
         subfield="Theoretical and surface chemistry",
         names=["Jens K. Nørskov", "Matthias Scheffler", "Thomas F. Jaramillo", "Manos Mavrikakis", "Jan Rossmeisl"],
         basis="The d-band model and scaling relations predict adsorption energies and catalytic activity trends.",
         rationale="Turned surface catalysis into a predictive, computational design discipline.",
         reservation="Builds on 2007 surface chemistry (Ertl) and 1998 DFT awards.",
         attribution="Nørskov is central; Scheffler (ab initio surface thermodynamics), Jaramillo (experimental validation), Mavrikakis and Rossmeisl.",
         sources=["Jens Nørskov"]),
    dict(src="c41", key="serial-femtosecond-crystallography",
         discovery="Serial femtosecond crystallography at X-ray free-electron lasers",
         subfield="Structural and physical chemistry",
         names=["Henry N. Chapman", "Janos Hajdu", "Petra Fromme", "Ilme Schlichting"],
         hist=[("John C. H. Spence", "Co-developer of serial femtosecond crystallography"),
               ("Richard Neutze", "Time-resolved XFEL structural dynamics; predicted diffraction-before-destruction")],
         basis="Femtosecond X-ray pulses record diffraction before radiation damage, enabling room-temperature and time-resolved structures.",
         rationale="Allows molecular movies of reactions in proteins.",
         reservation="Partly an instrument (physics) achievement; overlaps cryo-EM-era structural awards.",
         attribution="Hajdu (diffraction-before-destruction concept), Chapman and Fromme (first SFX, 2011), Schlichting.",
         sources=["Serial femtosecond crystallography"]),
    dict(src="c43", key="surface-sfg-spectroscopy",
         discovery="Surface-specific nonlinear vibrational spectroscopy of interfaces",
         subfield="Physical chemistry and spectroscopy",
         names=["Yuen-Ron Shen", "Mischa Bonn", "Geraldine L. Richmond", "Alexander Benderskii", "Tahei Tahara"],
         basis="Sum-frequency generation selectively probes molecules at interfaces such as water surfaces.",
         rationale="Primary tool for interfacial molecular structure.",
         reservation="Shen's contribution is primarily physics; credit beyond Shen is diffuse.",
         attribution="Shen invented SFG vibrational spectroscopy; others extended it to water and dynamics.",
         sources=["Sum frequency generation spectroscopy"]),
    dict(src="c45", key="single-molecule-spectroscopy",
         discovery="Optical detection and spectroscopy of single molecules in condensed phases",
         subfield="Physical chemistry and spectroscopy",
         names=["Michel Orrit", "Richard N. Zare"],
         hist=[("Urs P. Wild", "Single-molecule spectroscopy in solids")],
         basis="Single-molecule fluorescence detection in solids and solution removed ensemble averaging.",
         rationale="Basis of single-molecule chemistry and imaging.",
         reservation="Moerner's single-molecule detection was central to the 2014 prize; overlap is high.",
         attribution="Orrit (first single-molecule fluorescence excitation, 1990), Zare (single-molecule detection in solution).",
         prior=["Super-resolution fluorescence microscopy including Moerner's single-molecule work: Chemistry 2014; high overlap"],
         sources=["Michel Orrit"]),
    dict(src="c47", key="atomic-layer-deposition",
         discovery="Atomic layer deposition for atomically controlled thin films",
         subfield="Materials and surface chemistry",
         names=["Tuomo Suntola", "Markku Leskelä", "Steven M. George", "Riikka Puurunen"],
         basis="Sequential self-limiting surface reactions deposit films one atomic layer at a time.",
         rationale="Essential in semiconductor manufacturing.",
         reservation="An engineering-heavy achievement; Soviet molecular-layering priority (Aleskovskii) complicates credit.",
         attribution="Suntola invented ALE/ALD (1974); Leskelä and George developed chemistry; Puurunen (surface chemistry and history). Valentin Aleskovskii (molecular layering) is not in the pool: he is presumed deceased but this was not verified.",
         sources=["Atomic layer deposition", "Tuomo Suntola"]),
    dict(src="c49", key="droplet-microfluidics",
         discovery="Droplet microfluidics for compartmentalized chemistry and high-throughput assays",
         subfield="Analytical chemistry and microfluidics",
         names=["Andrew D. Griffiths", "David A. Weitz", "Stephen R. Quake", "Rustem F. Ismagilov", "George M. Whitesides"],
         basis="Microfluidic droplets act as picolitre reactors for screening and single-cell analysis.",
         rationale="Underlies digital PCR, single-cell sequencing and directed-evolution screens.",
         reservation="Diffuse credit; partly engineering.",
         attribution="Griffiths (in vitro compartmentalization), Weitz, Quake and Ismagilov (droplet platforms), Whitesides (soft-lithographic microfluidics).",
         sources=["Droplet-based microfluidics"]),
    dict(src="c50", key="superheavy-elements",
         discovery="Synthesis and characterization of the superheavy elements",
         subfield="Nuclear and radiochemistry",
         names=["Yuri Oganessian", "Kosuke Morita", "Kenton J. Moody", "Christoph E. Düllmann"],
         hist=[("Sigurd Hofmann", "Discovery of elements 107-112 at GSI")],
         basis="Hot- and cold-fusion reactions extended the periodic table to element 118.",
         rationale="Completed the seventh row of the periodic table.",
         reservation="More nuclear physics than chemistry; Oganessian is 93.",
         attribution="Oganessian (hot fusion, elements 114-118), Morita (nihonium), Moody (Livermore-Dubna collaboration), Düllmann (superheavy chemistry).",
         sources=["Superheavy element", "Yuri Oganessian"]),
    dict(src="c51", key="atmospheric-new-particle-formation",
         discovery="Atmospheric new-particle formation and the chemistry of secondary aerosol",
         subfield="Atmospheric and environmental chemistry",
         names=["Markku Kulmala", "José-Luis Jiménez", "Barbara J. Finlayson-Pitts", "Spyros N. Pandis", "Neil M. Donahue"],
         basis="Vapours nucleate and grow into aerosol particles that affect clouds, climate and health.",
         rationale="Key uncertainty in climate forcing.",
         reservation="Atmospheric chemistry was rewarded in 1995; credit is diffuse.",
         attribution="Kulmala (new-particle formation), Jiménez (aerosol mass spectrometry), Finlayson-Pitts (interfacial chemistry), Pandis and Donahue (volatility basis set).",
         prior=["Ozone chemistry: Chemistry 1995"],
         sources=["Aerosol"]),
    dict(src="c52", key="ionic-liquids",
         discovery="Ionic liquids and designer solvents",
         subfield="Physical and green chemistry",
         names=["Robin D. Rogers", "Joan F. Brennecke", "Tom Welton", "Andrew P. Abbott", "Michael J. Zaworotko"],
         hist=[("Kenneth R. Seddon", "Room-temperature ionic liquid chemistry")],
         basis="Room-temperature molten salts form tunable solvents for synthesis, separations and electrochemistry.",
         rationale="Widely used solvent class.",
         reservation="Seddon, the central figure, is dead; applications are diffuse.",
         attribution="Rogers (cellulose dissolution), Brennecke (CO2 capture), Welton, Abbott (deep eutectic solvents), Zaworotko (air-stable imidazolium salts with Wilkes, 1992). John S. Wilkes left out because living status could not be verified.",
         sources=["Ionic liquid"]),
    dict(src="c53", key="green-chemistry",
         discovery="Green chemistry and atom economy as design principles for synthesis",
         subfield="Green and synthetic chemistry",
         names=["Paul T. Anastas", "Barry M. Trost", "John C. Warner", "Robert H. Crabtree"],
         hist=[("Roger A. Sheldon", "E-factor metric")],
         basis="Atom economy and the twelve principles reframed synthesis around waste and hazard.",
         rationale="Changed industrial and academic practice.",
         reservation="A framework rather than a discovery; the Codex draft did not expand green chemistry.",
         attribution="Trost (atom economy, 1991), Anastas and Warner (twelve principles); Crabtree as alternative.",
         sources=["Green chemistry", "Atom economy"]),
    dict(src="c55", key="amyloid-structure",
         discovery="Structural chemistry of amyloid and protein misfolding",
         subfield="Structural and biophysical chemistry",
         names=["David S. Eisenberg", "Robert Tycko", "Roland Riek", "Michele Vendruscolo"],
         hist=[("Christopher M. Dobson", "Protein misfolding and amyloid formation")],
         basis="Atomic structures of amyloid fibrils reveal the cross-beta steric zipper.",
         rationale="Chemical basis of neurodegenerative diseases.",
         reservation="Dobson, a leading figure, is dead; cryo-EM fibril structures share credit.",
         attribution="Eisenberg (steric zippers), Tycko and Riek (solid-state NMR fibril structures), Vendruscolo (aggregation kinetics).",
         sources=["Amyloid", "David Eisenberg"]),
    dict(src="c56", key="riboswitches",
         discovery="Riboswitches and metabolite-sensing RNA structures",
         subfield="Nucleic acid chemistry",
         names=["Ronald R. Breaker", "Evgeny Nudler", "Adrian R. Ferré-D'Amaré"],
         basis="Structured mRNA elements bind metabolites directly to regulate gene expression without proteins.",
         rationale="Shows RNA as a sensor and supports the RNA world.",
         reservation="Narrower than other nucleic acid entries.",
         attribution="Breaker and Nudler (with Mironov) discovered riboswitches (2002); Ferré-D'Amaré (structures). Alexander Mironov left out because his identity and living status could not be verified.",
         sources=["Riboswitch"]),
    dict(src="c57", key="prebiotic-chemistry",
         discovery="Prebiotic synthesis of nucleotides and the chemistry of the RNA world",
         subfield="Prebiotic and synthetic chemistry",
         names=["John D. Sutherland", "Gerald F. Joyce", "Steven A. Benner", "Matthew W. Powner", "Jack W. Szostak", "David W. Deamer"],
         basis="Plausible prebiotic routes to nucleotides and self-replicating RNA support an RNA world.",
         rationale="Addresses chemical origins of life.",
         reservation="Origins of life remain unresolved.",
         attribution="Sutherland and Powner (pyrimidine nucleotide synthesis, 2009), Joyce (self-replicating ribozymes), Benner, Szostak (protocells), Deamer.",
         prior=["Szostak: Medicine 2009 for telomeres; distinct achievement"],
         sources=["RNA world"]),
    dict(src="c58", key="genetically-encoded-indicators",
         discovery="Genetically encoded fluorescent indicators for imaging cellular chemistry",
         subfield="Chemical biology and imaging",
         names=["Loren L. Looger", "Junichi Nakai", "Oliver Griesbeck", "Takeharu Nagai", "Lin Tian"],
         hist=[("Roger Y. Tsien", "Cameleon indicators; 2008 Chemistry laureate for GFP")],
         basis="Engineered fluorescent proteins report calcium, voltage and neurotransmitters in living cells.",
         rationale="Basis of modern neuroscience imaging.",
         reservation="GFP was rewarded in 2008; Tsien is dead.",
         attribution="Nakai (GCaMP, 2001), Griesbeck, Nagai, Looger and Tian (GCaMP optimization, neurotransmitter sensors).",
         prior=["Green fluorescent protein: Chemistry 2008"],
         sources=["GCaMP"]),
    dict(src="c59", key="cryo-electron-tomography",
         discovery="Cryo-electron tomography for in situ structural chemistry of cells",
         subfield="Structural chemistry and imaging",
         names=["Wolfgang Baumeister", "Jürgen M. Plitzko", "Elizabeth Villa", "John A. G. Briggs", "Abraham J. Koster"],
         basis="Tomography of vitrified cells, with FIB milling, resolves macromolecules in their native context.",
         rationale="Extends cryo-EM from purified molecules to cells.",
         reservation="Cryo-EM was rewarded in 2017; overlap is substantial.",
         attribution="Baumeister (founder), Plitzko and Villa (FIB lamella preparation), Briggs (subtomogram averaging), Koster (automated tomography).",
         prior=["Cryo-electron microscopy: Chemistry 2017; substantial overlap"],
         sources=["Cryogenic electron tomography"]),
    dict(src="c60", key="nitrogenase-mechanism",
         discovery="Structure and mechanism of nitrogenase",
         subfield="Bioinorganic and structural chemistry",
         names=["Douglas C. Rees", "Oliver Einsle", "Lance C. Seefeldt", "Dennis R. Dean", "Markus W. Ribbe"],
         basis="Structures and mechanisms of the FeMo-cofactor explain biological N2 reduction, including its interstitial carbide.",
         rationale="Central question in bioinorganic chemistry.",
         reservation="Mechanism is still incompletely resolved.",
         attribution="Rees (first structures), Einsle (interstitial carbon), Seefeldt and Dean (mechanism), Ribbe (cofactor biosynthesis).",
         sources=["Nitrogenase"]),
    dict(src="c61", key="oxygen-evolving-complex",
         discovery="Structure and mechanism of the oxygen-evolving complex of photosystem II",
         subfield="Bioinorganic and structural chemistry",
         names=["Jian-Ren Shen", "Johannes Messinger", "Vittal K. Yachandra", "Holger Dau", "Junko Yano"],
         basis="Atomic structures and spectroscopy of the Mn4CaO5 cluster explain photosynthetic water oxidation.",
         rationale="Nature's water-splitting catalyst.",
         reservation="Photosynthetic reaction centres were rewarded in 1988.",
         attribution="Shen (1.9 Å structure, with Kamiya and Kawakami), Messinger, Yachandra, Yano and Dau (spectroscopy).",
         prior=["Photosynthetic reaction centre: Chemistry 1988"],
         sources=["Oxygen-evolving complex"]),
    dict(src="c62", key="selective-fluorination",
         discovery="Methods for selective carbon-fluorine bond formation",
         subfield="Synthetic organic chemistry",
         names=["Véronique Gouverneur", "Tobias Ritter", "Melanie S. Sanford", "Shannon S. Stahl", "Stephen G. DiMagno"],
         basis="Catalytic and late-stage fluorination methods install C-F and C-18F bonds selectively.",
         rationale="Important for pharmaceuticals and PET tracers.",
         reservation="Methodology area with many contributors.",
         attribution="Gouverneur and Ritter (late-stage and 18F fluorination), Sanford, Stahl, DiMagno.",
         sources=["Electrophilic fluorination", "Véronique Gouverneur"]),
    dict(src="c66", key="capillary-electrophoresis",
         discovery="Capillary electrophoresis for high-resolution chemical and genomic separations",
         subfield="Analytical chemistry",
         names=["James W. Jorgenson", "Norman J. Dovichi", "Barry L. Karger", "Richard A. Mathies"],
         basis="Narrow capillaries give high-efficiency electrophoretic separations, enabling capillary DNA sequencers.",
         rationale="Made the Human Genome Project's sequencing throughput possible.",
         reservation="Superseded for sequencing by NGS.",
         attribution="Jorgenson (1981 capillary zone electrophoresis), Dovichi, Karger and Mathies (capillary array sequencing). Stellan Hjertén left out because living status could not be verified.",
         sources=["Capillary electrophoresis"]),
    dict(src="c67", key="enzyme-electrode-biosensors",
         discovery="Electrical wiring of enzymes to electrodes and amperometric biosensing",
         subfield="Electrochemistry and analytical chemistry",
         names=["Adam Heller", "Anthony P. F. Turner", "George S. Wilson", "Lo Gorton"],
         hist=[("H. Allen O. Hill", "Ferrocene-mediated glucose sensing")],
         basis="Redox polymers and mediators connect enzyme active sites to electrodes.",
         rationale="Underlies glucose meters and continuous glucose monitors.",
         reservation="Partly engineering; credit includes industrial developers.",
         attribution="Heller (wired enzymes, continuous glucose monitor), Turner and Hill (mediated glucose sensor), Wilson and Gorton.",
         sources=["Adam Heller", "Glucose meter"]),
    dict(src="c69", key="pet-radiochemistry",
         discovery="Fluorine-18 radiochemistry and the synthesis of PET radiotracers",
         subfield="Radiochemistry",
         names=["Joanna S. Fowler", "Tatsuo Ido"],
         hist=[("Alfred P. Wolf", "18F-FDG synthesis program"), ("Michael J. Welch", "PET radiochemistry"),
               ("Henry N. Wagner Jr.", "Nuclear medicine imaging")],
         basis="Synthesis of 18F-fluorodeoxyglucose enabled PET imaging of metabolism.",
         rationale="Widely used clinical imaging chemistry.",
         reservation="Many pioneers are dead; could be seen as medicine.",
         attribution="Ido and Fowler synthesized 18F-FDG at Brookhaven (1976-78) with Wolf. Tatsuo Ido's living status is not confirmed.",
         sources=["Fluorodeoxyglucose (18F)", "Joanna Fowler"]),
    dict(src="c71", key="dna-charge-transport",
         discovery="Long-range charge transport through DNA",
         subfield="Bioinorganic and physical chemistry",
         names=["Jacqueline K. Barton", "Bernd Giese", "Gary B. Schuster", "Frederick D. Lewis"],
         basis="The base-pair stack mediates long-range charge transport.",
         rationale="Fundamental electron-transfer chemistry with proposed roles in DNA repair.",
         reservation="Biological significance is still debated.",
         attribution="Barton (DNA-mediated charge transport), Giese (hopping mechanism), Schuster (phonon-assisted polaron hopping), Lewis (dynamics).",
         sources=["Jacqueline Barton"]),
    dict(src="c73", key="semiconductor-nanowires",
         discovery="Rational synthesis of semiconductor nanowires for nanoscale devices",
         subfield="Materials chemistry and nanoscience",
         names=["Charles M. Lieber", "Peidong Yang", "Lars Samuelson", "Hongkun Park"],
         basis="Catalyst-directed growth gives nanowires of controlled composition for electronics and photonics.",
         rationale="Building blocks for nanoelectronics, sensors and solar fuels.",
         reservation="Lieber's 2021 criminal conviction may weigh on consideration.",
         attribution="Lieber (rational synthesis and devices), Yang (nanowire lasers, photonics), Samuelson (epitaxial nanowire heterostructures), Park.",
         conflict=["Committee chair Heiner Linke (Lund/NanoLund) works on semiconductor nanowires and is a probable coauthor of Lars Samuelson; verify before dispatch."],
         sources=["Nanowire", "Charles M. Lieber"]),
    dict(src="c74", key="gold-catalysis",
         discovery="Catalysis by gold",
         subfield="Catalysis",
         names=["Graham J. Hutchings", "F. Dean Toste", "A. Stephen K. Hashmi"],
         hist=[("Masatake Haruta", "Low-temperature CO oxidation on supported gold nanoparticles")],
         basis="Supported gold nanoparticles and gold complexes are active catalysts despite gold's bulk inertness.",
         rationale="Created heterogeneous and homogeneous gold catalysis.",
         reservation="Haruta, the co-discoverer, is dead; heterogeneous and homogeneous branches are separable.",
         attribution="Hutchings (acetylene hydrochlorination prediction), Toste and Hashmi (homogeneous gold catalysis).",
         sources=["Graham Hutchings"]),
    dict(src="c76", key="nc-afm-chemical-bonds",
         discovery="Imaging the chemical structure of single molecules by noncontact atomic force microscopy",
         subfield="Surface chemistry and microscopy",
         names=["Leo Gross", "Gerhard Meyer", "Franz J. Giessibl", "Wilson Ho", "Donald M. Eigler"],
         basis="CO-functionalized tips resolve bonds within single molecules and follow on-surface reactions.",
         rationale="Direct visualization of molecular structure and reactions.",
         reservation="Builds on STM (Physics 1986) and AFM; related to the Codex AFM entry.",
         attribution="Gross and Meyer (pentacene bond imaging, 2009), Giessibl (qPlus sensor), Ho (single-molecule chemistry with STM), Eigler (atom manipulation).",
         prior=["STM: Physics 1986"],
         sources=["Non-contact atomic force microscopy", "Scanning tunneling microscope"]),
    dict(src="c77", key="sers-ters",
         discovery="Single-molecule surface-enhanced and tip-enhanced Raman spectroscopy",
         subfield="Physical chemistry and spectroscopy",
         names=["Shuming Nie", "Katrin Kneipp", "Renato Zenobi", "Zhong-Qun Tian"],
         hist=[("Richard P. Van Duyne", "Discovery of surface-enhanced Raman scattering"),
               ("Martin Fleischmann", "First SERS observation")],
         basis="Plasmonic enhancement allows Raman spectra of single molecules and nanoscale chemical imaging.",
         rationale="Ultrasensitive vibrational analysis.",
         reservation="SERS discoverers are dead.",
         attribution="Nie and Kneipp (single-molecule SERS, 1997), Zenobi (TERS), Tian (shell-isolated SERS).",
         sources=["Surface-enhanced Raman spectroscopy", "Tip-enhanced Raman spectroscopy"]),
    dict(src="c79", key="orbitrap",
         discovery="The Orbitrap mass analyzer",
         subfield="Analytical chemistry",
         names=["Alexander A. Makarov"],
         basis="Ions orbiting an electrostatic spindle electrode give high-resolution mass measurement.",
         rationale="Dominant high-resolution analyzer in proteomics and metabolomics.",
         reservation="An instrument invention by a single industrial scientist.",
         attribution="Makarov invented the Orbitrap (2000).",
         sources=["Orbitrap"]),
    dict(src="c81", key="native-mass-spectrometry",
         discovery="Native mass spectrometry of intact protein complexes",
         subfield="Analytical and structural chemistry",
         names=["Carol V. Robinson", "Albert J. R. Heck", "Joseph A. Loo", "Brian T. Chait", "Michael L. Gross"],
         basis="Gentle ionization preserves non-covalent assemblies, including membrane protein complexes with lipids.",
         rationale="Structural biology by mass spectrometry.",
         reservation="Electrospray ionization was rewarded in 2002.",
         attribution="Robinson (membrane complexes), Heck, Loo (early native MS), Chait, Gross.",
         prior=["Electrospray/MALDI: Chemistry 2002"],
         sources=["Carol Robinson"]),
    dict(src="c83", key="machine-learned-potentials",
         discovery="Machine-learned interatomic potentials for atomistic simulation",
         subfield="Theoretical and computational chemistry",
         names=["Jörg Behler", "Gábor Csányi", "Michele Parrinello", "Albert P. Bartók", "O. Anatole von Lilienfeld", "Weinan E"],
         basis="Neural-network and kernel potentials reproduce quantum accuracy at near force-field cost.",
         rationale="Transforming molecular and materials simulation.",
         reservation="Very recent; follows the 2024 AI-structure award.",
         attribution="Behler and Parrinello (neural-network potentials, 2007), Csányi and Bartók (Gaussian approximation potentials), von Lilienfeld, E (deep potentials).",
         prior=["Computational protein design and structure prediction: Chemistry 2024"],
         sources=["Machine-learned interatomic potential"]),
    dict(src="c84", key="conical-intersections",
         discovery="Conical intersections as funnels in photochemical reactions",
         subfield="Theoretical chemistry and photochemistry",
         names=["Michael A. Robb", "Todd J. Martínez", "Massimo Olivucci"],
         hist=[("Josef Michl", "Funnels in photochemical reaction paths")],
         basis="Degeneracies between electronic states channel ultrafast radiationless decay in photochemistry.",
         rationale="Central concept in photochemistry and vision.",
         reservation="Michl, a central pioneer, is dead.",
         attribution="Robb (with Bernardi and Olivucci, computational characterization), Martínez (ab initio multiple spawning). Fernando Bernardi and David Yarkony left out because living status could not be verified.",
         sources=["Conical intersection"]),
    dict(src="c85", key="energy-landscape-folding",
         discovery="Energy landscape theory and experimental mapping of protein folding",
         subfield="Theoretical and biophysical chemistry",
         names=["Peter G. Wolynes", "José N. Onuchic", "Alan R. Fersht", "Joseph D. Bryngelson", "Ken A. Dill"],
         basis="Funnel-shaped energy landscapes and phi-value analysis explain how proteins fold.",
         rationale="Resolved Levinthal's paradox.",
         reservation="Codex lists chaperone-assisted folding separately; 2024 structure prediction is related.",
         attribution="Wolynes, Onuchic and Bryngelson (landscape theory), Fersht (phi-value analysis), Dill (folding funnels).",
         sources=["Folding funnel", "Peter Guy Wolynes"]),
    dict(src="c86", key="pks-nrps-enzymology",
         discovery="Enzymology of modular polyketide and nonribosomal peptide biosynthesis",
         subfield="Biological chemistry",
         names=["Chaitan Khosla", "Mohamed A. Marahiel", "David A. Hopwood", "Peter F. Leadlay"],
         hist=[("Christopher T. Walsh", "Mechanistic enzymology of natural product assembly lines")],
         basis="Assembly-line enzymes build antibiotics module by module and can be reprogrammed.",
         rationale="Chemistry of natural product biosynthesis.",
         reservation="Walsh, the central figure, is dead.",
         attribution="Hopwood and Leadlay (modular PKS genetics), Khosla (engineered biosynthesis), Marahiel (NRPS).",
         sources=["Polyketide synthase", "Nonribosomal peptide"]),
    dict(src="c87", key="radical-enzymology",
         discovery="Radical enzymology: protein radicals in ribonucleotide reductase and radical SAM enzymes",
         subfield="Biological and bioinorganic chemistry",
         names=["JoAnne Stubbe", "Joan B. Broderick", "Squire J. Booker", "Britt-Marie Sjöberg", "Perry A. Frey"],
         basis="Enzymes generate and control radicals for hard reactions such as ribonucleotide reduction.",
         rationale="Fundamental mechanistic enzymology.",
         reservation="Narrower than broad structural entries.",
         attribution="Stubbe (RNR radical mechanism), Sjöberg (tyrosyl radical), Frey (radical SAM discovery), Broderick and Booker. Peter Reichard (RNR discovery) is not in the pool: he is believed deceased but this was not verified.",
         conflict=["Committee member Andrei Chabes works on ribonucleotide reductase regulation (not in this pool); Britt-Marie Sjöberg is a Stockholm University RNR researcher. Verify relationships before dispatch."],
         sources=["JoAnne Stubbe", "Radical SAM enzymes"]),
    dict(src="c88", key="oxygen-activation-metalloenzymes",
         discovery="Mechanisms of oxygen activation by iron and copper enzymes",
         subfield="Bioinorganic chemistry",
         names=["Edward I. Solomon", "Lawrence Que Jr.", "J. Martin Bollinger Jr.", "Carsten Krebs", "Judith P. Klinman"],
         basis="Spectroscopy and trapped intermediates define how metalloenzymes activate O2.",
         rationale="Central bioinorganic mechanism.",
         reservation="Diffuse credit.",
         attribution="Solomon (spectroscopy), Que (non-heme iron models), Bollinger and Krebs (Fe(IV)-oxo intermediates), Klinman (tunneling).",
         sources=["Edward I. Solomon"]),
    dict(src="c89", key="kras-covalent-inhibitors",
         discovery="Covalent drugging of mutant KRAS and chemical genetics of kinases",
         subfield="Chemical biology and medicinal chemistry",
         names=["Kevan M. Shokat"],
         basis="Covalent ligands to a pocket in KRAS G12C made a long 'undruggable' oncogene druggable.",
         rationale="Led to approved drugs (sotorasib, adagrasib).",
         reservation="Drug development involved many industrial scientists.",
         attribution="Shokat (2013 KRAS G12C switch-II pocket; analog-sensitive kinases).",
         sources=["Kevan Shokat", "Sotorasib"]),
    dict(src="c91", key="therapeutic-oligonucleotide-chemistry",
         discovery="Chemical modification and targeted delivery of therapeutic oligonucleotides",
         subfield="Nucleic acid and medicinal chemistry",
         names=["Muthiah Manoharan", "Stanley T. Crooke", "Jesper Wengel", "Takeshi Imanishi", "Peter E. Nielsen"],
         hist=[("Fritz Eckstein", "Phosphorothioate nucleotide chemistry")],
         basis="Backbone, sugar and conjugate modifications made antisense and siRNA drugs stable and deliverable.",
         rationale="Basis of approved oligonucleotide medicines.",
         reservation="Eckstein, a key pioneer, died in 2026; the Medicine list carries an antisense SMN2 entry.",
         attribution="Manoharan (GalNAc conjugates), Crooke (antisense drugs), Wengel and Imanishi (locked nucleic acids), Nielsen (peptide nucleic acid). Takeshi Imanishi's living status is not confirmed.",
         sources=["Oligonucleotide", "Locked nucleic acid"]),
    dict(src="c92", key="self-labeling-tags",
         discovery="Self-labeling protein tags and bright synthetic fluorophores for live-cell imaging",
         subfield="Chemical biology and imaging",
         names=["Kai Johnsson", "Luke D. Lavis", "Keith V. Wood", "Alice Y. Ting"],
         hist=[("Roger Y. Tsien", "Biarsenical tags")],
         basis="Tags such as SNAP and Halo covalently capture synthetic dyes, and improved fluorophores give bright imaging.",
         rationale="Standard tools in imaging and super-resolution.",
         reservation="Overlaps 2008 (GFP) and 2014 (super-resolution).",
         attribution="Johnsson (SNAP-tag), Wood (HaloTag), Lavis (Janelia Fluor dyes), Ting (enzyme-mediated labeling).",
         prior=["GFP: Chemistry 2008", "Super-resolution microscopy: Chemistry 2014"],
         sources=["SNAP-tag", "HaloTag"]),
    dict(src="c93", key="smrt-sequencing",
         discovery="Single-molecule real-time DNA sequencing in zero-mode waveguides",
         subfield="Analytical and nucleic acid chemistry",
         names=["Jonas Korlach", "Stephen W. Turner", "Harold G. Craighead"],
         hist=[("Watt W. Webb", "Zero-mode waveguide concept")],
         basis="Nanophotonic wells observe single polymerases incorporating labeled nucleotides.",
         rationale="Long-read sequencing and direct detection of base modifications.",
         reservation="Competes with nanopore and short-read sequencing entries.",
         attribution="Korlach, Turner, Craighead and Webb (zero-mode waveguides, 2003).",
         sources=["Single-molecule real-time sequencing"]),
    dict(src="c94", key="light-directed-synthesis-microarrays",
         discovery="Light-directed parallel chemical synthesis and DNA microarrays",
         subfield="Analytical and combinatorial chemistry",
         names=["Stephen P. A. Fodor", "Edwin M. Southern", "Patrick O. Brown", "Michael C. Pirrung", "J. Leighton Read"],
         basis="Photolithographic synthesis and spotted arrays measure many nucleic-acid hybridizations in parallel.",
         rationale="Enabled genome-wide expression and genotyping.",
         reservation="Largely superseded by sequencing.",
         attribution="Fodor, Pirrung and Read (light-directed synthesis, 1991), Southern (array hybridization), Brown (spotted arrays).",
         sources=["DNA microarray"]),
    dict(src="c95", key="spin-labeling-epr",
         discovery="Site-directed spin labeling and pulsed EPR distance measurements",
         subfield="Magnetic resonance and physical chemistry",
         names=["Wayne L. Hubbell", "Gunnar Jeschke", "Jack H. Freed", "Hassane S. Mchaourab"],
         basis="Spin labels on engineered sites report structure, and pulsed EPR measures nanometre distances.",
         rationale="Structural dynamics of membrane proteins.",
         reservation="Specialist method.",
         attribution="Hubbell (site-directed spin labeling), Jeschke and Freed (pulsed dipolar spectroscopy), Mchaourab. Yuri Tsvetkov (DEER) left out because living status could not be verified.",
         sources=["Site-directed spin labeling"]),
    dict(src="c96", key="mad-phasing",
         discovery="Multiwavelength anomalous diffraction phasing in macromolecular crystallography",
         subfield="Structural chemistry",
         names=["Wayne A. Hendrickson", "Janet L. Smith"],
         hist=[("Roger Fourme", "Anomalous dispersion methods")],
         basis="Anomalous scattering at tuned synchrotron wavelengths, with selenomethionine, solves the phase problem.",
         rationale="Solved most new protein structures for decades.",
         reservation="Direct methods were rewarded in 1985.",
         attribution="Hendrickson (MAD and selenomethionine), Smith.",
         prior=["Direct methods: Chemistry 1985"],
         sources=["Wayne Hendrickson"]),
    dict(src="c98", key="nucleosome-structure",
         discovery="Atomic structure of the nucleosome core particle",
         subfield="Structural chemistry",
         names=["Timothy J. Richmond", "Karolin Luger"],
         hist=[("Aaron Klug", "Early nucleosome structure; 1982 Chemistry laureate")],
         basis="The 2.8 Å nucleosome structure showed how histones package DNA.",
         rationale="Structural basis of chromatin and epigenetics.",
         reservation="Kornberg discovered the nucleosome and won in 2006 (for transcription); Klug won in 1982.",
         attribution="Luger and Richmond (1997 structure). Roger Kornberg (nucleosome discovery, 1974) is a prior laureate and is not in the pool.",
         prior=["Klug: Chemistry 1982", "Kornberg: Chemistry 2006"],
         sources=["Nucleosome", "Karolin Luger"]),
    dict(src="c99", key="single-molecule-magnets",
         discovery="Single-molecule magnets",
         subfield="Inorganic and materials chemistry",
         names=["Roberta Sessoli", "George Christou", "Richard A. Layfield"],
         hist=[("Dante Gatteschi", "Discovery of Mn12 single-molecule magnetism")],
         basis="Individual molecules show magnetic hysteresis and quantum tunneling of magnetization.",
         rationale="Bridges molecular chemistry and magnetism.",
         reservation="Gatteschi died in August 2026; applications remain speculative.",
         attribution="Sessoli (with Gatteschi, Mn12, 1993), Christou (manganese clusters), Layfield (dysprosocenium near 80 K).",
         sources=["Single-molecule magnet"]),
    dict(src="c100", key="main-group-multiple-bonds",
         discovery="Stable multiple bonds and low-valent compounds of the heavier main-group elements",
         subfield="Main-group chemistry",
         names=["Philip P. Power", "Akira Sekiguchi", "Gregory H. Robinson"],
         hist=[("Robert West", "First stable Si=Si double bond, 1981")],
         basis="Bulky ligands stabilize multiple bonds and low oxidation states of heavier p-block elements.",
         rationale="Overturned the double-bond rule; main-group compounds mimic transition metals.",
         reservation="Fundamental but with limited applications; West is dead.",
         attribution="Power (heavier alkyne analogues), Sekiguchi (Si≡Si triple bond), Robinson (carbene-stabilized diatomics).",
         sources=["Philip Power"]),
    dict(src="c101", key="bulk-heterojunction-opv",
         discovery="Bulk-heterojunction organic photovoltaics and molecular electron acceptors",
         subfield="Materials and organic chemistry",
         names=["N. Serdar Sariciftci", "Fred Wudl", "Xiaowei Zhan", "Alan J. Heeger", "Gang Yu"],
         basis="Photoinduced polymer-to-fullerene electron transfer and blended heterojunctions make solution-processed solar cells.",
         rationale="Organic photovoltaics exceeding 19% efficiency with non-fullerene acceptors.",
         reservation="Heeger already won in 2000 for conducting polymers; commercial impact is limited.",
         attribution="Sariciftci, Heeger and Wudl (photoinduced electron transfer, 1992), Yu (bulk heterojunction), Zhan (non-fullerene acceptor ITIC). Jonathan Halls (parallel polymer blend cells) left out because living status could not be verified.",
         prior=["Heeger: Chemistry 2000 for conducting polymers"],
         sources=["Organic solar cell"]),
    dict(src="c102", key="stretchable-electronics",
         discovery="Flexible and stretchable electronic materials",
         subfield="Materials chemistry",
         names=["Zhenan Bao", "John A. Rogers", "Takao Someya"],
         basis="Molecular and structural design yields semiconductors and circuits that bend and stretch like skin.",
         rationale="Wearable and implantable electronics.",
         reservation="Recent and application-oriented.",
         attribution="Bao (stretchable polymer semiconductors), Rogers (stretchable inorganic electronics), Someya (electronic skin).",
         sources=["Zhenan Bao", "Stretchable electronics"]),
    dict(src="c103", key="aggregation-induced-emission",
         discovery="Aggregation-induced emission",
         subfield="Photochemistry and materials chemistry",
         names=["Ben Zhong Tang"],
         basis="Some molecules emit only when aggregated, because restricted intramolecular motion blocks non-radiative decay.",
         rationale="Very widely used luminogens for sensing and imaging.",
         reservation="Mechanistically related phenomena were known earlier.",
         attribution="Tang coined and developed AIE (2001).",
         sources=["Aggregation-induced emission"]),
    dict(src="c104", key="battery-electrolytes",
         discovery="Solid and polymer electrolytes and electrode interphases in batteries",
         subfield="Electrochemistry and materials chemistry",
         names=["Michel Armand", "Ryoji Kanno", "Emanuel Peled", "Peter G. Bruce"],
         basis="Polymer and sulfide solid electrolytes, and the solid-electrolyte interphase, control lithium battery chemistry.",
         rationale="Basis of solid-state batteries and stable lithium cells.",
         reservation="Lithium-ion batteries were rewarded in 2019.",
         attribution="Armand (polymer electrolytes, LiTFSI salts), Kanno (LGPS superionic conductors), Peled (SEI model), Bruce. Peter V. Wright left out because living status could not be verified.",
         prior=["Lithium-ion batteries: Chemistry 2019; overlap review"],
         sources=["Michel Armand", "Solid-state electrolyte"]),
    dict(src="c105", key="autonomic-self-healing",
         discovery="Autonomic self-healing polymers",
         subfield="Polymer chemistry",
         names=["Nancy R. Sottos", "Jeffrey S. Moore"],
         hist=[("Scott R. White", "Microcapsule self-healing composites, 2001")],
         basis="Embedded healing agents and dynamic bonds let materials repair damage.",
         rationale="Opened self-healing materials.",
         reservation="White, the lead author of the 2001 discovery, is dead; related to the vitrimer entry.",
         attribution="White, Sottos and Moore (microencapsulated healing agent, 2001).",
         sources=["Self-healing material"]),
]

# Committee-adjacent topics deliberately not added.
EXCLUDED_FOR_COMMITTEE = [
    ("3D electron diffraction / microED for small-molecule and protein structures", "Xiaodong Zou is in the credit pool."),
    ("Free-energy simulations of biomolecules and ligand binding", "Johan Åqvist is in the credit pool."),
    ("Proton pumping by cytochrome c oxidase", "Peter Brzezinski works directly on it."),
]
DROPPED_FOR_DEATH = [
    ("Surface science of heterogeneous catalysis", "Gabor A. Somorjai died 2025-07-07; Gerhard Ertl already won in 2007."),
    ("Single-molecule electronics", "Mark A. Ratner died 2026-05-10 and Mark A. Reed died 2021-05-05."),
    ("Synthetic genomics", "J. Craig Venter, Hamilton O. Smith and Clyde A. Hutchison III all died (2026, 2025, 2025)."),
]


# ---------------------------------------------------------------- trim
# Entries removed from the simulation list (kept on record in the JSON).
PRIOR = "Substantial overlap with an already rewarded achievement"
DEAD = "The central discoverer(s) have died"
MED = "Biology-centred or already covered by the Medicine list"
BROAD = "A broad field or programme rather than a defined discovery"
NARROW = "Narrower, superseded or weaker than retained entries in the same area"
TRIM = {
    "covalent-organic-frameworks": PRIOR, "tetrazine-ligation": PRIOR, "single-molecule-spectroscopy": PRIOR,
    "hydrogen-bond-donor-catalysis": PRIOR, "cryo-electron-tomography": PRIOR, "transcription-machinery": PRIOR,
    "single-molecule-mechanics": PRIOR, "atomic-force-microscopy": PRIOR, "crispr-adaptive-immunity": PRIOR,
    "mad-phasing": PRIOR, "oxygen-evolving-complex": PRIOR, "nucleosome-structure": PRIOR,
    "battery-electrolytes": PRIOR, "bulk-heterojunction-opv": PRIOR, "supramolecular-polymers": PRIOR,
    "gold-catalysis": DEAD, "single-site-olefin-polymerization": DEAD, "ionic-liquids": DEAD,
    "pks-nrps-enzymology": DEAD, "pet-radiochemistry": DEAD, "single-molecule-magnets": DEAD,
    "main-group-multiple-bonds": DEAD, "amyloid-structure": DEAD, "autonomic-self-healing": DEAD,
    "conical-intersections": DEAD, "sers-ters": DEAD,
    "optogenetics": MED, "chaperone-assisted-folding": MED, "quorum-sensing": MED, "spatial-transcriptomics": MED,
    "clarity": MED, "genetically-encoded-indicators": MED, "riboswitches": MED, "expansion-microscopy": MED,
    "transthyretin-stabilization": MED,
    "green-chemistry": BROAD, "polymeric-controlled-release": BROAD, "complex-natural-product-synthesis": BROAD,
    "solar-fuels-catalysts": BROAD, "atmospheric-new-particle-formation": BROAD, "droplet-microfluidics": BROAD,
    "oxygen-activation-metalloenzymes": BROAD, "molecular-nitrogen-fixation": BROAD, "selective-fluorination": BROAD,
    "stretchable-electronics": BROAD,
    "smrt-sequencing": NARROW, "light-directed-synthesis-microarrays": NARROW, "capillary-electrophoresis": NARROW,
    "crystalline-sponges": NARROW, "nanoporous-supercapacitors": NARROW, "mass-spectrometry-imaging": NARROW,
    "enzyme-electrode-biosensors": NARROW, "spin-labeling-epr": NARROW, "dna-charge-transport": NARROW,
    "prebiotic-chemistry": NARROW, "radical-enzymology": NARROW, "double-network-hydrogels": NARROW,
    "gas-phase-catalytic-mechanisms": NARROW, "self-labeling-tags": NARROW, "automated-glycan-assembly": NARROW,
    "surface-sfg-spectroscopy": NARROW, "electrochemical-co2-reduction": NARROW, "vitrimers": NARROW,
}

# ---------------------------------------------------------------- build
def dedupe(names: list[str]) -> list[str]:
    seen, out = set(), []
    for n in names:
        if norm(n) not in seen:
            seen.add(norm(n))
            out.append(n)
    return out


dead = {norm(n) for n in DEATHS}
entries = []
for cid, c in CX.items():
    m = MERGE.get(cid, {})
    drop = {norm(n) for n in m.get("drop", [])}
    names = [n for n in c["credited_names"] if norm(n) not in drop]
    added = [n for n in m.get("add", []) if norm(n) not in {norm(x) for x in names}]
    names = dedupe(names + added)
    hist_entries = [hist(h["name"], CODEX_HIST_CONTRIB.get(h["name"], ""), h["source_ids"])
                    for h in c["historical_contributors"]]
    hist_entries += [hist(n, contrib) for n, contrib in m.get("hist", [])]
    note = c["attribution_note"] + (" " + m["note"] if m.get("note") else "")
    inputs = [{"list_id": "chemistry-2026-codex", "candidate_id": cid}]
    inputs += [{"list_id": "claude-opus-5", "candidate_id": x} for x in m.get("claude", [])]
    if m.get("claude"):
        decision = "Merged shared discovery; Codex scope and sources retained" + (
            "; Claude names added to the pool." if added else "; no Claude names added.")
    else:
        decision = "Retained Codex-only discovery."
    entries.append({
        "discovery_key": c["discovery_key"],
        "discovery": m.get("discovery", c["discovery"]),
        "subfield": m.get("subfield", c["subfield"]),
        "credited_names": names,
        "scientific_basis": c["scientific_basis"],
        "rationale": c["rationale"],
        "main_reservation": c["main_reservation"],
        "attribution_note": note,
        "source_ids": list(c["source_ids"]),
        "conflict_flags": list(c["conflict_flags"]) + m.get("conflict", []),
        "inclusion_status": c.get("inclusion_status", "retained"),
        "input_entries": inputs,
        "review_decision": decision,
        "attribution_additions": added,
        "historical_contributors": hist_entries,
        "prior_award_flags": list(c["prior_award_flags"]),
    })

used_claude = {x for m in MERGE.values() for x in m.get("claude", [])} | {e["src"] for e in CL_ONLY}
missing = set(CL) - used_claude
assert not missing, f"unmapped Claude entries: {sorted(missing)}"

for e in CL_ONLY:
    entries.append({
        "discovery_key": e["key"],
        "discovery": e["discovery"],
        "subfield": e["subfield"],
        "credited_names": dedupe(e["names"]),
        "scientific_basis": e["basis"],
        "rationale": e["rationale"],
        "main_reservation": e["reservation"],
        "attribution_note": e["attribution"],
        "source_ids": [wiki(t) for t in e["sources"]],
        "conflict_flags": e.get("conflict", []),
        "inclusion_status": "retained",
        "input_entries": [{"list_id": "claude-opus-5", "candidate_id": e["src"]}],
        "review_decision": "Retained Claude-only discovery; pool combines Claude nominees and living other_names.",
        "attribution_additions": [],
        "historical_contributors": [hist(n, contrib) for n, contrib in e.get("hist", [])],
        "prior_award_flags": e.get("prior", []),
    })

entries.sort(key=lambda e: e["discovery"].casefold())
keys = [e["discovery_key"] for e in entries]
assert len(keys) == len(set(keys)), "duplicate discovery keys"
assert set(TRIM) <= set(keys), f"unknown trim keys: {sorted(set(TRIM) - set(keys))}"
trimmed = [{"discovery_key": e["discovery_key"], "discovery": e["discovery"], "credited_names": e["credited_names"],
            "input_entries": e["input_entries"], "trim_reason": TRIM[e["discovery_key"]]}
           for e in entries if e["discovery_key"] in TRIM]
entries = [e for e in entries if e["discovery_key"] not in TRIM]
for i, e in enumerate(entries, start=1):
    e["candidate_id"] = f"CH{i:03d}"
    e["assessment_type"] = "author_judgment_not_probability"
    e["name_pool_status"] = "provisional_attribution_pool_not_actual_nominations"
    e["review_status"] = "merged_draft_living_status_checked"
    bad = [n for n in e["credited_names"] if norm(n) in dead]
    assert not bad, f"{e['candidate_id']} has deceased names in pool: {bad}"
    assert e["credited_names"], e["candidate_id"]
    for sid in e["source_ids"] + [s for h in e["historical_contributors"] for s in h["source_ids"]]:
        assert sid in SOURCES, f"{e['candidate_id']}: unknown source {sid}"

used_sources = sorted({s for e in entries for s in e["source_ids"]} |
                      {s for e in entries for h in e["historical_contributors"] for s in h["source_ids"]})

shared = sum(1 for cid in CX if MERGE.get(cid, {}).get("claude"))
out = {
    "schema_version": 1,
    "category": "chemistry",
    "prize_year": 2026,
    "list_id": "chemistry-2026",
    "version": 1,
    "prepared_by": "Claude (claude-opus-5-5) consolidation of the Codex and Claude drafts",
    "research_cutoff": "2026-10-03",
    "cutoff_timezone": "America/Chicago",
    "source_type": "consolidated_author_researched_longlist",
    "nominator_stage": {"status": "omitted", "simulated_nominations": False, "actual_nominations_known": False},
    "inputs": [
        {"list_id": "chemistry-2026-codex", "path": "agent-data/chemistry/candidates/codex/candidates.json",
         "candidate_count": len(CX)},
        {"list_id": "claude-opus-5", "path": "agent-data/chemistry/candidates/claude-opus-5/candidates.json",
         "candidate_count": len(CL)},
    ],
    "merge_summary": {
        "codex_input_entries": len(CX),
        "claude_input_entries": len(CL),
        "codex_entries_matched_by_claude": shared,
        "codex_only_discoveries": len(CX) - shared,
        "claude_only_discoveries": len(CL_ONLY),
        "consolidated_discoveries": len(entries) + len(trimmed),
        "trimmed_discoveries": len(trimmed),
        "retained_discoveries": len(entries),
        "dropped_input_entries": 0,
    },
    "candidate_count": len(entries),
    "candidate_order": "alphabetical_by_discovery_not_rank",
    "scope": "Discovery-centered union of both drafts. Credit pools are provisional and can exceed three; agents must select a coherent award of no more than three people in total. No ranking, probabilities or nominator counts are implied.",
    "limitations": [
        "Recipient pools are evidence-informed starting points, not exhaustive priority judgments.",
        "Living status was checked against Wikidata and Wikipedia for every pooled name on 2026-10-03, but many younger researchers have no registry entry; absence of a death record is not proof of living status. Recheck shortlisted recipients before final selection.",
        "Claude-only entries cite Wikipedia overviews rather than primary or award sources; Codex entries keep their original sources.",
        "Prior laureates can appear in a pool for a distinct achievement and are marked in prior_award_flags; already rewarded achievements need explicit overlap review.",
        "Some entries are cross-category (optogenetics, chaperones, quorum sensing) or overlap the Medicine list; this is intentional coverage.",
        "Committee coauthorship flags (zeolites, nanowires) need handling before simulation dispatch.",
        "The union was trimmed to a simulation-sized list; trimmed_entries records each removed discovery and the reason.",
    ],
    "excluded_for_committee_overlap": [{"topic": t, "reason": r} for t, r in EXCLUDED_FOR_COMMITTEE],
    "dropped_for_deceased_key_figures": [{"topic": t, "reason": r} for t, r in DROPPED_FOR_DEATH],
    "trimmed_entries": trimmed,
    "candidates": entries,
    "sources": {k: SOURCES[k] for k in used_sources},
}
(OUT / "candidates.json").write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n")

with (OUT / "candidates.csv").open("w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["candidate_id", "discovery", "subfield", "credited_names"])
    for e in entries:
        w.writerow([e["candidate_id"], e["discovery"], e["subfield"], "; ".join(e["credited_names"])])

lines = [
    "# Attribution and scope review of the consolidated Chemistry list", "",
    "Union of the Codex draft (72 entries) and the Claude draft (106 entries), 3 October 2026, trimmed for simulation (trimmed entries are listed at the end). "
    "Shared discoveries are merged by achievement; Codex's separations (ATRP/RAFT, base/prime editing, "
    "fluorescent/phosphorescent OLEDs, Car-Parrinello/metadynamics, alkane C-H activation/selective C-H "
    "functionalization, carbon supercapacitors/MXenes) are kept. Inclusion is not a ranking.", "",
]
for e in entries:
    lines += [f"## {e['candidate_id']} — {e['discovery']}", "",
              f"**Credit pool:** {'; '.join(e['credited_names'])}.", "",
              f"**Input entries:** {'; '.join(i['list_id'] + ':' + i['candidate_id'] for i in e['input_entries'])}.", "",
              f"**Decision:** {e['review_decision']}", "",
              f"**Scientific basis:** {e['scientific_basis']}", "",
              f"**Attribution judgment:** {e['attribution_note']}", "",
              f"**Reservation:** {e['main_reservation']}", ""]
    if e["historical_contributors"]:
        lines += ["**Historical credit only:** " + "; ".join(
            f"{h['name']} ({h['death_date'] or 'deceased'})" for h in e["historical_contributors"]) + ".", ""]
    if e["prior_award_flags"]:
        lines += ["**Prior-award flags:** " + "; ".join(e["prior_award_flags"]) + ".", ""]
    if e["conflict_flags"]:
        lines += ["**Committee flags:** " + " ".join(e["conflict_flags"]), ""]
    lines += ["**Evidence:** " + "; ".join(
        f"[{SOURCES[s]['title']}]({SOURCES[s]['url']})" for s in e["source_ids"]) + ".", ""]
lines += ["## Not added because of committee overlap", ""] + [f"- **{t}:** {r}" for t, r in EXCLUDED_FOR_COMMITTEE]
lines += ["", "## Dropped because key figures have died", ""] + [f"- **{t}:** {r}" for t, r in DROPPED_FOR_DEATH]
for reason in (PRIOR, DEAD, MED, BROAD, NARROW):
    lines += ["", f"## Trimmed: {reason.lower()}", ""]
    lines += [f"- {t['discovery']} ({'; '.join(t['credited_names'])})" for t in trimmed if t["trim_reason"] == reason]
(OUT / "attribution_review.md").write_text("\n".join(lines) + "\n")

print(f"{len(entries)} retained, {len(trimmed)} trimmed (union {len(entries) + len(trimmed)}: {shared} shared, {len(CX) - shared} Codex-only, {len(CL_ONLY)} Claude-only); "
      f"{len({norm(n) for e in entries for n in e['credited_names']})} distinct pooled names; "
      f"{len(used_sources)} sources")
